### ISSUE TITLE
Interested in developing LiteLoader version, but unsure of licensing restrictions

### ISSUE THREAD

**Issue by bradland** [stephank/mcdisablewheel#2]
I'm not even sure if it's possible, but I was considering porting this mod to [LiteLoader](https://www.assembla.com/spaces/liteloader/wiki), rather than relying on MCPatcher. However, there is no license indicated in the source code, so I obviously don't want to violate your work :)

If you are unsure of what license to use, I would humbly suggest the [MIT license](http://opensource.org/licenses/MIT).

**Comment by stephank** [comment]
It's MIT licensed, as mentioned on the readme, Good luck!
