### ISSUE TITLE
MCDisableScrollWheel Incompatible with Java 6

### ISSUE THREAD

**Issue by jetblackrx89** [stephank/mcdisablewheel#3]
MCDisableScrollWheel was compiled for Java 7 and will be ignored in MCPatcher if you're using Java 6. The workaround is to temporarily upgrade to Java 7 when patching.

javap -v mcdisablewheel.DisableMouseWheel
Classfile .../mcdisablewheel/DisableMouseWheel.class
Last modified Feb 4, 2014; size 792 bytes
MD5 checksum f54353aeb2b6940ae968cf38fa78ab67
Compiled from "DisableMouseWheel.java"
public final class mcdisablewheel.DisableMouseWheel extends
com.prupe.mcpatcher.Mod
SourceFile: "DisableMouseWheel.java"
- minor version: 0 major version: 51\* flags: ACC_PUBLIC, ACC_FINAL,
  ACC_SUPER

Most executable .jar files used for Minecraft patching are still compiled for Java 6 because it has an active userbase. Is there any chance we can see the same for this mod?

**Comment by stephank** [comment]
I just uploaded 0.4. Can you try again with that version?

http://stephan.kochen.nl/public/mcdisablewheel/MCDisableWheel-0.4.jar

**Comment by jetblackrx89** [comment]
It works fine now. Thanks for the quick response time and for this very useful mod.
